config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :payments

  resources :virtual_machines

  resources :storage_spaces

  resources :rack_spaces

  resources :locations

  resources :servers

  resources :services

  resources :service_types

    root 'pages#home'

end

app/models/server.rb
class Server < ActiveRecord::Base
    has_many :virtual_machines
    has_many :storage_spaces
    belongs_to :location
    belongs_to :service
    
    def get_hd_used()
        hdcap = self.hd
        hdused = 0
        self.virtual_machines.each do |vm|
            hdused += vm.hd
        end
        self.storage_spaces.each do |stor|
            hdused += stor.amount
        end
        hdused_perc = hdused.to_f / hdcap * 100
        hdused_perc
    end
    
    def get_mem_used()
        memcap = self.mem
        memused = 0
        self.virtual_machines.each do |vm|
            memused += vm.mem
        end
        memused_perc = memused.to_f / memcap * 100
        memused_perc
    end
    
    def get_cpu_used()
        cpucap = self.cpu
        cpuused = 0
        self.virtual_machines.each do |vm|
            cpuused += vm.cpu
        end
        cpuused_perc = cpuused.to_f / cpucap * 100
        cpuused_perc
    end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :model, :hd, :mem, :cpu, :os, :size, :location_id, :service_id)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="panel">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :hd %><br>
    <%= f.number_field :hd %>
  </div>
  <div class="field">
    <%= f.label :mem %><br>
    <%= f.number_field :mem %>
  </div>
  <div class="field">
    <%= f.label :cpu %><br>
    <%= f.number_field :cpu %>
  </div>
  <div class="field">
    <%= f.label :os %><br>
    <%= f.text_field :os %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :service_id %><br>
    <%= f.number_field :service_id %>
  </div>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <th>Hd</th>
      <th>Mem</th>
      <th>Cpu</th>
      <th>Os</th>
      <th>Size (U)</th>
      <th>Location</th>
      <th>Service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.model %></td>
        <td><%= server.hd %></td>
        <td><%= server.mem %></td>
        <td><%= server.cpu %></td>
        <td><%= server.os %></td>
        <td><%= server.size %></td>
        <td><%= server.location.room %></td>
        <td><%= server.service_id %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel">
    <h4>Services hosted on this server</h4>
    <h5>Virtual Machines</h5>
    <p>
        <% @server.virtual_machines.each do |vm| %>
            <li><%= link_to vm.hostname, virtual_machine_path(vm) %></li>
        <% end %>
    </p>
    
    <h5>Storage Space</h5>
    <p>
        <% @server.storage_spaces.each do |space| %>
            <li><%= link_to space.amount, storage_space_path(space) %></li>    
        <% end %>
    </p>
</div>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @server.model %>
</p>

<p>
  <strong>Hd:</strong>
  <%= @server.hd %>
</p>

<p>
  <strong>Mem:</strong>
  <%= @server.mem %>
</p>

<p>
  <strong>Cpu:</strong>
  <%= @server.cpu %>
</p>

<p>
  <strong>Os:</strong>
  <%= @server.os %>
</p>

<p>
  <strong>Size:</strong>
  <%= @server.size %>
</p>

<p>
  <strong>Location:</strong>
  <%= @server.location_id %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>