config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :payments

  resources :virtual_machines

  resources :storage_spaces

  resources :rack_spaces

  resources :locations

  resources :servers

  resources :services

  resources :service_types

    root 'pages#home'

end

app/models/location.rb
class Location < ActiveRecord::Base
    has_many :servers
    has_many :rack_spaces
    
    def get_used()
        used = 0
        self.rack_spaces.each do |rs|
            used += rs.size
        end
        self.servers.each do |s|
            used += s.size
        end
        used / self.capacity.to_f * 100
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
    belongs_to :service
    belongs_to :user
end

app/models/rack_space.rb
class RackSpace < ActiveRecord::Base
    belongs_to :server
    belongs_to :service
    accepts_nested_attributes_for :service
end

app/models/server.rb
class Server < ActiveRecord::Base
    has_many :virtual_machines
    has_many :storage_spaces
    belongs_to :location
    belongs_to :service
    
    def get_hd_used()
        hdcap = self.hd
        hdused = 0
        self.virtual_machines.each do |vm|
            hdused += vm.hd
        end
        self.storage_spaces.each do |stor|
            hdused += stor.amount
        end
        hdused_perc = hdused.to_f / hdcap * 100
        hdused_perc
    end
    
    def get_mem_used()
        memcap = self.mem
        memused = 0
        self.virtual_machines.each do |vm|
            memused += vm.mem
        end
        memused_perc = memused.to_f / memcap * 100
        memused_perc
    end
    
    def get_cpu_used()
        cpucap = self.cpu
        cpuused = 0
        self.virtual_machines.each do |vm|
            cpuused += vm.cpu
        end
        cpuused_perc = cpuused.to_f / cpucap * 100
        cpuused_perc
    end
end

app/models/service.rb
class Service < ActiveRecord::Base
    has_one :server
    has_one :rack_space
    has_one :storage_space
    has_one :virtual_machine
    has_one :user
    has_many :payments
    
    def get_payment_total()
        total = 0
        self.payments.each do |p|
            total += p.amount
        end
        total
    end
    
    def get_balance()
        total = self.get_payment_total()
        balance = self.cost - total
        balance
    end
    
    def self.get_expiring()
        Service.where("enddate <= ?", Date.today + 6.month)
    end
    
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
end

app/models/storage_space.rb
class StorageSpace < ActiveRecord::Base
    belongs_to :server
    belongs_to :service
    accepts_nested_attributes_for :service
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :payments
    has_many :services
end

app/models/virtual_machine.rb
class VirtualMachine < ActiveRecord::Base
    belongs_to :server
    belongs_to :service
    accepts_nested_attributes_for :service
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:admin, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rack_spaces_helper.rb
module RackSpacesHelper
    def setup_rackspace(rackspace)
        rackspace.service ||= Service.new
        rackspace
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/storage_spaces_helper.rb
module StorageSpacesHelper
    def setup_space(space)
        space.service ||= Service.new
        space
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <%= render 'shared/navigation' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar>
    <ul class="title-area">
        <li class="name">
            <h1><%= link_to 'MAD Service Tracker', root_path %></h1>
        </li>
    </ul>
    
    <section class="top-bar-section">
        <ul class="left">
            <li><%= link_to 'Servers', servers_path %></li>
            <li><%= link_to 'Virtual Machines', virtual_machines_path %></li>
            <li><%= link_to 'Storage Space', storage_spaces_path %></li>
            <li><%= link_to 'Rack Space', rack_spaces_path %></li>
            <li><%= link_to 'Billing',  services_path %></li>
        </ul>
    </section>
    
    <section class="top-bar-section">
        <ul class="right">
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Locations', locations_path %></li>
        </ul>
    </section>
    
</nav>